### ISSUE TITLE
Projectile delayed return to pool after hitting a platform

### ISSUE THREAD

**Issue by Teru5244** [JimmyC7834/U.stick-battle-arena#35]
@JimmyC7834 As the title, if a bullet hits a wall instead of a player, it will remain on the wall for seconds and then return to the wall, collision and hit damage is still effective while on the wall. (main branch)

**Comment by Teru5244** [comment]
It seems the problem is that the `HandleHitStage()` never gets called when a projectile hits a wall. It will stay on the wall until its lifespan runs out.

**Comment by JimmyC7834** [comment]
The problem has been solved. However, there are more bugs on pooling bullet objects and I'm investigating.
