### ISSUE TITLE
Players can't come back to screen after stepping out.

### ISSUE THREAD

**Issue by jaredtran2001** [JimmyC7834/U.stick-battle-arena#68]
When playing I would walk out of bounds and I would either expect to die or to be able to walk back in but instead I'm in a state of the game where nothing occurs and there is no way to reset the game.

**Comment by ZaynabKhan** [comment]
I noticed the same issue. If I walked off a short distance off-screen, I could come back, but not for long distances.

**Comment by JimmyC7834** [comment]
This is simply because there's no boundary around the map and the player could just walk outside of the map.
In the release version this situation should be fixed by proper stage design.
