### ISSUE TITLE
Daytime has only 1 life but nighttime has 5.

### ISSUE THREAD

**Issue by ZaynabKhan** [JimmyC7834/U.stick-battle-arena#69]
In daytime, the game ends when one player loses 1 life but in nighttime, the players have 5 lives. The counter for daytime goes directly 5 lives to 0 lives. The counter in nighttime goes 5, 4, 3, 2, 1.

**Comment by JimmyC7834** [comment]
This is normal behavior for testing. And also to show that we can have different gameplay settings under different stages.
