### ISSUE TITLE
Daytime Player 2 starts offscreen.

### ISSUE THREAD

**Issue by ZaynabKhan** [JimmyC7834/U.stick-battle-arena#70]
This could be a simple positioning bug, but I cannot see Player 2 when I start daytime mode. I use the left arrow key to bring it on screen. This issue is not there in nighttime.

**Comment by JimmyC7834** [comment]
This is caused by the animator not being updated with an empty default visual.
Thanks for the issue.

**Comment by JimmyC7834** [comment]
Fixed in new visual update #66
